### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by alocket2** [soffes/GradientView#17]
Im trying to achieve a certain style with the radial gradient.
Is there anyway to do hard color stops instead of blending so I can get an effect [like this](http://imgur.com/rswQr96)

Thanks

**Comment by Prarik** [comment]
May be this is useful - http://stackoverflow.com/questions/31853859/radial-gradient-background-in-swift

**Comment by soffes** [comment]
You could implement this by setting custom locations on GradientView using the techniques linked above.
