### ISSUE TITLE
Not working with swift 2.3 

### ISSUE THREAD

**Issue by Pikacz** [soffes/GradientView#19]
UIGraphicsGetCurrentContext and CGColorSpaceCreateDeviceRGB returns optional values

change line 135 to 
guard let context = UIGraphicsGetCurrentContext() else { return }

and line 212 to
guard let cgColorSpace = CGColorGetColorSpace(cgColor) else { return }

or similar

**Comment by soffes** [comment]
Swift 2.3 is not supported.
