### ISSUE TITLE
Unsuccessful pod update with 2.3.2. version

### ISSUE THREAD

**Issue by opotapov-sygic** [soffes/GradientView#35]
#Got the massage
[!] The platform of the target `AppTarget` (iOS 10.0) is not compatible with `GradientView (2.3.2)`, which does not support `ios`.

I suppose, something is wrong with namings in .xcscheme [in this commit](https://github.com/soffes/GradientView/commit/7e04d2f16148e12ea4ef25a895b2ad62c7ca0675?diff=split) , because 2.3.1. works for me.

**Comment by soffes** [comment]
Fixed in version 2.3.3. Thanks for reporting!
