### ISSUE TITLE
using UIColor.whiteColor() as the first color sets gradient color space to UIDeviceWhiteColorSpace

### ISSUE THREAD

**Issue by chadkouse** [soffes/GradientView#7]
Meaning sending white, then say red as your colors you end up with a greyscale gradient instead of white->red

Line in question:
https://github.com/soffes/GradientView/blob/master/GradientView/GradientView.swift#L199

**Comment by chadkouse** [comment]
Workaround is to use
```swift
UIColor(red:1.0, green:1.0, blue:1.0, alpha:1.0)
```
instead of `UIColor.whiteColor()`

**Comment by soffes** [comment]
Ya, known issue :( I guess I could convert everything to RGB internally

**Comment by chadkouse** [comment]
If you try to use UIColor.whiteColor() in the RGB color space, what happens?  I'm thinking maybe you could just iterate the colors looking for to see if there are multiple color spaces in use and if any of them are RGB then just use RGB for everything?  I don't know much about how colorspaces work when you have colors from different color spaces mixed together.
